using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace UnderwaterCity.Model1
{
    internal class Font
    {
        // Generated by IconFont2Code: https://andreinitescu.github.io/IconFont2Code
        // If you change the class to 'public' in order to use it outside its assembly
        //  you should also change the fields from 'const' to 'public static readonly'
        static class IconFont
        {
            public const string Icon1 = "\u0040";
            public const string Icon2 = "\u0057";
            public const string Icon3 = "\u0056";
            public const string Icon4 = "\u0055";
            public const string Icon5 = "\u004e";
            public const string Icon6 = "\u004a";
            public const string Icon7 = "\u007b";
            public const string Icon8 = "\u007d";
            public const string Icon9 = "\u005b";
            public const string Icon10 = "\u005d";
            public const string Icon11 = "\u0028";
            public const string Icon12 = "\u0029";
            public const string Icon13 = "\u0049";
            public const string Icon14 = "\u0059";
            public const string Icon15 = "\u0050";
            public const string Icon16 = "\u0046";
            public const string Icon17 = "\u0054";
            public const string Icon18 = "\u0026";
            public const string Icon19 = "\u0048";
            public const string Icon20 = "\u004d";
            public const string Icon21 = "\u0058";
            public const string Icon22 = "\u0052";
            public const string Icon23 = "\u0071";
            public const string Icon24 = "\u0041";
            public const string Icon25 = "\u004b";
            public const string Icon26 = "\u0024";
            public const string Icon27 = "\u0077";
            public const string Icon28 = "\u0025";
            public const string Icon29 = "\u0027";
            public const string Icon30 = "\u0060";
            public const string Icon31 = "\u004c";
            public const string Icon32 = "\u0022";
            public const string Icon33 = "\u006f";
            public const string Icon34 = "\u0039";
            public const string Icon35 = "\u0034";
            public const string Icon36 = "\u0078";
            public const string Icon37 = "\u0072";
            public const string Icon38 = "\u0063";
            public const string Icon39 = "\u0062";
            public const string Icon40 = "\u0074";
            public const string Icon41 = "\u0073";
            public const string Icon42 = "\u0036";
            public const string Icon43 = "\u0076";
            public const string Icon44 = "\u0075";
            public const string Icon45 = "\u007a";
            public const string Icon46 = "\u0061";
            public const string Icon47 = "\u0067";
            public const string Icon48 = "\u0033";
            public const string Icon49 = "\u0038";
            public const string Icon50 = "\u006d";
            public const string Icon51 = "\u0032";
            public const string Icon52 = "\u0035";
            public const string Icon53 = "\u0030";
            public const string Icon54 = "\u006c";
            public const string Icon55 = "\u006e";
            public const string Icon56 = "\u006b";
            public const string Icon57 = "\u0037";
            public const string Icon58 = "\u0064";
            public const string Icon59 = "\u0065";
            public const string Icon60 = "\u006a";
            public const string Icon61 = "\u0079";
            public const string Icon62 = "\u0068";
            public const string Icon63 = "\u0070";
            public const string Icon64 = "\u002f";
            public const string Icon65 = "\u005c";
            public const string Icon66 = "\u0066";
            public const string Icon67 = "\u003f";
            public const string Icon68 = "\u0023";
            public const string Icon69 = "\u003d";
            public const string Icon70 = "\u002d";
            public const string Icon71 = "\u002b";
            public const string Icon72 = "\u002a";
            public const string Icon73 = "\u0021";
            public const string Icon74 = "\u0031";
            public const string Icon75 = "\u003c";
            public const string Icon76 = "\u003e";
            public const string Icon77 = "\u0069";
            public const string Icon78 = "\u002c";
            public const string Icon79 = "\u002e";
            public const string Icon80 = "\u003b";
            public const string Icon81 = "\u003a";
            public const string Icon82 = "\u0042";
            public const string Icon83 = "\u0043";
            public const string Icon84 = "\u0044";
            public const string Icon85 = "\u0045";
            public const string Icon86 = "\u0047";
            public const string Icon87 = "\u004f";
            public const string Icon88 = "\u0051";
            public const string Icon89 = "\u0053";
            public const string Icon90 = "\u005a";
            public const string Icon91 = "\u0020";
        }
    }
}
